# Generated by Django 5.0 on 2026-05-22 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, verbose_name='size')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='price')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmm.brand', verbose_name='brand')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmm.maker', verbose_name='maker')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmm.scale', verbose_name='scale')),
                ('tags', models.ManyToManyField(blank=True, related_name='kits', to='pmm.tag', verbose_name='tags')),
            ],
        ),
        migrations.CreateModel(
            name='CreationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_date', models.DateField(auto_now_add=True, verbose_name='get_date')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmm.kit', verbose_name='kit')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmm.maker', verbose_name='maker'),
        ),
    ]
