# Generated by Django 5.0 on 2026-05-22 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creationstatus',
            name='get_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='get_date'),
        ),
    ]
