# Generated by Django 5.0 on 2026-05-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmm', '0002_alter_creationstatus_get_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='maker',
        ),
    ]
