# Generated by Django 5.0 on 2026-05-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmm', '0003_remove_kit_maker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creationstatus',
            name='status',
            field=models.CharField(choices=[('backlog', '積み'), ('in_progress', '製作中'), ('completed', '完成'), ('on_hold', '中断')], default='backlog', max_length=20, verbose_name='status'),
        ),
    ]
