# Generated by Django 5.0 on 2026-05-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmm', '0004_add_creationstatus_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creationstatus',
            name='status',
            field=models.CharField(choices=[('backlog', '積み'), ('in_progress', '製作中'), ('completed', '完成'), ('on_hold', '中断'), ('sold', '売却済み'), ('parted_out', '素材化')], default='backlog', max_length=20, verbose_name='status'),
        ),
    ]
