# Generated by Django 5.0 on 2026-05-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmm', '0005_add_sold_partedout_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kits/', verbose_name='image'),
        ),
    ]
