# Generated by Django 5.0 on 2026-05-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmm', '0006_kit_image_to_imagefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='creationstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
    ]
