# Generated by Django 5.0 on 2026-05-29 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmm', '0008_add_owner_to_kit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pmm.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pmm.maker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_makers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'maker')},
            },
        ),
    ]
